baseURL = "http://www.synthfeeder.com/"
languageCode = "en-us"
title = "Synthfeeder"
theme = "ananke"
SectionPagesMenu = "main"
googleAnalytics = "UA-141901466-1"
enableRobotsTXT = true
DefaultContentLanguage = "en"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "logo.png"
  description = "Music creation tools"
  twitter = "https://twitter.com/synthfeeder"
  facebook = "https://www.facebook.com/synthfeeder"
  background_color_class = "bg-black"
  googleFonts = "https://fonts.googleapis.com/css?family=Lato:300|Open+Sans:300|Source+Code+Pro:200&display=swap"
  custom_css = ["css/fonts.css"]
  cover_dimming_class = "bg-black-30"